// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TuPenca.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608004835_AddChatMessages")]
    partial class AddChatMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TuPenca.Domain.Entities.Administrador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Deporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Deportes");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.EventoDeportivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeporteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TipoCompetenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeporteId");

                    b.HasIndex("TipoCompetenciaId");

                    b.ToTable("EventosDeportivos");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Invitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aceptada")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AdministradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailInvitado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SitioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("SitioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Invitaciones");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.MensajeChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PencaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PencaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MensajesChat");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PencaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PencaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.Property<Guid>("PencaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PencaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Partido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EquipoGanadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoLocalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoVisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventoDeportivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalMatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResultadoLocal")
                        .HasColumnType("int");

                    b.Property<int?>("ResultadoVisitante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoGanadorId");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.HasIndex("EventoDeportivoId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Penca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlantillaPencaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PorcentajePremio1")
                        .HasColumnType("int");

                    b.Property<int>("PorcentajePremio2")
                        .HasColumnType("int");

                    b.Property<int>("PorcentajePremio3")
                        .HasColumnType("int");

                    b.Property<Guid>("SitioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlantillaPencaId");

                    b.HasIndex("SitioId");

                    b.ToTable("Pencas");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.PlantillaPenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventoDeportivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MontoEntrada")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PorcentajeComision")
                        .HasColumnType("int");

                    b.Property<int>("PuntajeGanador")
                        .HasColumnType("int");

                    b.Property<int>("TiempoLimitePrevioMinutos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoDeportivoId");

                    b.ToTable("PlantillasPenca");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Prediccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EquipoGanadorPredichoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("GolesLocal")
                        .HasColumnType("int");

                    b.Property<int>("GolesVisitante")
                        .HasColumnType("int");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PencaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipoGanadorPredichoId");

                    b.HasIndex("PartidoId");

                    b.HasIndex("PencaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Predicciones");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Premio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.Property<Guid>("PencaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsuarioGanadorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PencaId");

                    b.HasIndex("UsuarioGanadorId");

                    b.ToTable("Premios");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.PuntajeUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PencaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PuntosPartido")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.HasIndex("PencaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PuntajesUsuario");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.ReglaPuntuacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Desviacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlantillaPencaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantillaPencaId");

                    b.ToTable("ReglasPuntuacion");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Sitio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorPrimario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorSecundario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfiguracionSitio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlPropia")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UrlPropia")
                        .IsUnique();

                    b.ToTable("Sitios");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.TipoCompetencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposCompetencia");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FcmToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProveedorAuth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SitioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SitioId");

                    b.HasIndex("Email", "SitioId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.EventoDeportivo", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.Deporte", "Deporte")
                        .WithMany("Eventos")
                        .HasForeignKey("DeporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.TipoCompetencia", "TipoCompetencia")
                        .WithMany("Eventos")
                        .HasForeignKey("TipoCompetenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deporte");

                    b.Navigation("TipoCompetencia");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Invitacion", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.Administrador", null)
                        .WithMany("Invitaciones")
                        .HasForeignKey("AdministradorId");

                    b.HasOne("TuPenca.Domain.Entities.Sitio", "Sitio")
                        .WithMany("Invitaciones")
                        .HasForeignKey("SitioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sitio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.MensajeChat", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.Penca", "Penca")
                        .WithMany("Mensajes")
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Mensajes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Penca");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.Penca", "Penca")
                        .WithMany("Notificaciones")
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Penca");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Pago", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.Penca", "Penca")
                        .WithMany()
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Pagos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Penca");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Partido", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.Equipo", "EquipoGanador")
                        .WithMany()
                        .HasForeignKey("EquipoGanadorId");

                    b.HasOne("TuPenca.Domain.Entities.Equipo", "EquipoLocal")
                        .WithMany("PartidosComoLocal")
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.Equipo", "EquipoVisitante")
                        .WithMany("PartidosComoVisitante")
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.EventoDeportivo", "Evento")
                        .WithMany("Partidos")
                        .HasForeignKey("EventoDeportivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipoGanador");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Penca", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.PlantillaPenca", "Plantilla")
                        .WithMany("Pencas")
                        .HasForeignKey("PlantillaPencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.Sitio", "Sitio")
                        .WithMany("Pencas")
                        .HasForeignKey("SitioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plantilla");

                    b.Navigation("Sitio");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.PlantillaPenca", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.EventoDeportivo", "Evento")
                        .WithMany("Plantillas")
                        .HasForeignKey("EventoDeportivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Prediccion", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.Equipo", "EquipoGanadorPredicho")
                        .WithMany()
                        .HasForeignKey("EquipoGanadorPredichoId");

                    b.HasOne("TuPenca.Domain.Entities.Partido", "Partido")
                        .WithMany("Predicciones")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.Penca", "Penca")
                        .WithMany()
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Predicciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipoGanadorPredicho");

                    b.Navigation("Partido");

                    b.Navigation("Penca");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Premio", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.Penca", "Penca")
                        .WithMany("Premios")
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.Usuario", "UsuarioGanador")
                        .WithMany()
                        .HasForeignKey("UsuarioGanadorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Penca");

                    b.Navigation("UsuarioGanador");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.PuntajeUsuario", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.Penca", "Penca")
                        .WithMany("Puntajes")
                        .HasForeignKey("PencaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TuPenca.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Puntajes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("Penca");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.ReglaPuntuacion", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.PlantillaPenca", "Plantilla")
                        .WithMany("Reglas")
                        .HasForeignKey("PlantillaPencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plantilla");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("TuPenca.Domain.Entities.Sitio", "Sitio")
                        .WithMany("Usuarios")
                        .HasForeignKey("SitioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sitio");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Administrador", b =>
                {
                    b.Navigation("Invitaciones");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Deporte", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Equipo", b =>
                {
                    b.Navigation("PartidosComoLocal");

                    b.Navigation("PartidosComoVisitante");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.EventoDeportivo", b =>
                {
                    b.Navigation("Partidos");

                    b.Navigation("Plantillas");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Partido", b =>
                {
                    b.Navigation("Predicciones");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Penca", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Notificaciones");

                    b.Navigation("Premios");

                    b.Navigation("Puntajes");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.PlantillaPenca", b =>
                {
                    b.Navigation("Pencas");

                    b.Navigation("Reglas");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Sitio", b =>
                {
                    b.Navigation("Invitaciones");

                    b.Navigation("Pencas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.TipoCompetencia", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("TuPenca.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pagos");

                    b.Navigation("Predicciones");

                    b.Navigation("Puntajes");
                });
#pragma warning restore 612, 618
        }
    }
}
